### ISSUE TITLE
Data labels

### ISSUE THREAD

**Issue by syedhammadahmed** [Leminhbinh0209/KidYoutubeVideo#1]
HI,
In [data/YOUTUBE_data](https://github.com/Leminhbinh0209/Samba/tree/master/data/YOUTUBE_data) where can we find the class labels?

Thank you.

**Comment by Leminhbinh0209** [comment]
Hi, Please see our website to download our dataset: https://sites.google.com/view/samba-kids/home

**Comment by syedhammadahmed** [comment]
Sure, thank you.
